const menu = [
    {
      id: 1,
      title: 'Beef noodle soup (Pho Bo)',
      category: 'dinner',
      price: 20.99,
      img: 'images/menu/product-01.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Panaeng Curry',
      category: 'lunch',
      price: 13.99,
      img: 'images/menu/product-03.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'Cheese Cake',
      category: 'dessert',
      price: 6.99,
      img: 'images/menu/product-02.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Summer rolls',
      category: 'breakfast',
      price: 10.99,
      img: 'images/menu/product-04.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'Korea Gimpap',
      category: 'lunch',
      price: 22.99,
      img: 'images/menu/product-09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Blueberry muffin',
      category: 'dessert',
      price: 5.99,
      img: 'images/menu/product-05.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Chicken salad',
      category: 'breakfast',
      price: 8.99,
      img: 'images/menu/product-06.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Pork grib',
      category: 'lunch',
      price: 20.99,
      img: 'images/menu/product-10.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Stir-fried glass noodle',
      category: 'lunch',
      price: 16.99,
      img: 'images/menu/product-17.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;